# Generated by Django 3.0 on 2020-07-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200729_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgot_password_token',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
