# Generated by Django 3.0 on 2020-07-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_activate_token',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
